server.port=8084

grpc.client.order-service.address=static://localhost:50051
grpc.client.order-service.negotiationType=PLAINTEXT

grpc.client.kitchen-service.address=static://localhost:50052
grpc.client.kitchen-service.negotiationType=PLAINTEXT

grpc.client.account-service.address=static://localhost:50053
grpc.client.account-service.negotiationType=PLAINTEXT